services:
  traefik:
    image: traefik:v2.10
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpChallenge=true" # Use HTTP challenge for Let's Encrypt
      - "--certificatesresolvers.myresolver.acme.httpChallenge.entryPoint=web" # Use "web" for challenges
      - "--certificatesresolvers.myresolver.acme.email=valentin.billa@proton.me" # Your email for Let's Encrypt
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json" # Persistent storage for certs
    ports:
      - "80:80"       # Redirects HTTP traffic
      - "443:443"     # For HTTPS traffic
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt" # Store TLS certificates
    networks:
      - web
    labels:
      - "traefik.http.routers.traefik.rule=Host(`vbilla.fr`)"
      - "traefik.http.routers.traefik.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

  frontend:
    build:
      context: ./frontend  # Path to the React app's Dockerfile
      dockerfile: Dockerfile
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`mosaics.vbilla.fr`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
      - "traefik.http.routers.api.tls.certresolver=myresolver" # Use the Let's Encrypt certresolver
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/mosaics:/app/mosaics
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`api.mosaics.vbilla.fr`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls=true"
      - "traefik.http.services.backend.loadbalancer.server.port=80"
      - "traefik.http.routers.api.tls.certresolver=myresolver" # Use the Let's Encrypt certresolver
    restart: always

volumes:
  letsencrypt:

networks:
  web:
